#!/usr/bin/env python3
"""Tell if a database is in a different Odoo version than the running code.

The check itself is Odoo's own ``list_db_incompatible`` function, this script
only locates it because it moved in Odoo 20:

- Odoo <= 19: ``odoo.service.db.list_db_incompatible``
- Odoo >= 20: the function has been moved next to the database manager
  controller, cf. odoo/odoo@34ff401b "[MOV] core, web: database manager
  functions next to the controllers"

      ``odoo.addons.web.controllers.database.list_db_incompatible``

Usage:
    python /odoo/scripts/is_db_incompatible.py <db_name>

It prints True or False on stdout, so it can be used from the
start-entrypoint.d scripts:

    IS_DB_INCOMPATIBLE=$(python /odoo/scripts/is_db_incompatible.py $DB_NAME)
"""

import sys


def get_list_db_incompatible():
    """Return Odoo's own ``list_db_incompatible(databases)`` function."""
    try:
        # Odoo <= 19: exposed by the database RPC service
        from odoo.service.db import list_db_incompatible
    except ImportError:
        # Odoo >= 20: the function now lives in the database manager
        # controller, importing it requires the addons_path of the
        # configuration (ODOO_RC is set by the odoo images and points to the
        # config file generated by the entrypoint)
        from odoo.tools import config

        config.parse_config(setup_logging=False)
        try:
            from odoo.addons.web.controllers.database import list_db_incompatible
        except ImportError as exc:
            raise ImportError(
                "Odoo's list_db_incompatible was not found, neither in "
                "odoo.service.db (Odoo <= 19) nor in "
                "odoo.addons.web.controllers.database (Odoo >= 20, is the "
                "'web' addon in ADDONS_PATH ?)"
            ) from exc
    return list_db_incompatible


def is_db_incompatible(db_name):
    """Return True if ``db_name`` is not in the version of the running code"""
    return len(get_list_db_incompatible()((db_name,))) > 0


if __name__ == "__main__":
    print(is_db_incompatible(sys.argv[1]))
