#!/bin/bash

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database $DB_NAME does not exist, ignoring script"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    echo "Database $DB_NAME not initialized, ignoring script"
    exit 0
fi

IS_DB_INCOMPATIBLE=$(python -c "from odoo import service; print(len(service.db.list_db_incompatible(('$DB_NAME',))) > 0)")

if [ $IS_DB_INCOMPATIBLE == "False" ]
then
    # "Database $DB_NAME is in the good version nothing to do exiting."
    exit 0
fi

# is db installed ?

# if odoo < 14.0 this will not work because openupgrade has changed
# see openupgrade docs

# ensure openupgrade_scripts are available
if [ ! -d "/odoo/links/openupgrade_scripts/" ]
then
    echo "openupgrade_scripts not in the path."
    echo "Ensure openupgrade in spec.yaml"
    exit 1
fi

# load odoo to make sure openupgrade modules are available from odoo.
# it's more robus than just checking the addons path
# if they are not available, we may print some garbage to stdout
# so, we only should test if the result is True
# get_module_path() is present in v14 up to v17
# check if it's still reliable in future versions
IS_OPENUPGRADE_AVAILABLE=$(python -c 'from odoo import modules, tools; tools.config.parse_config(); print(modules.get_module_path("openupgrade_framework") and modules.get_module_path("openupgrade_scripts"))')

if [ $IS_OPENUPGRADE_AVAILABLE ]
then
    # we force --load to not load sentry or queue_job
    # we don't care with pooling / pgbouncer issues here
    echo "START OPENUPGRADE MIGRATION"

    # echo "erase log before starting the"
    rm -f /data/odoo/shared/migration.log
    # exit on failure
    # it may fail if the migration is not ready yet

    odoo --logfile=/data/odoo/shared/migration.log --update all --upgrade-path=/odoo/links/openupgrade_scripts/scripts --load=base,web,openupgrade_framework --stop-after-init || exit 1
    exit 0
else
    echo "Openupgrade framework or scripts not available !"
    exit 1
fi
