#!/bin/bash
set -eu -o pipefail

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database $DB_NAME does not exist, ignoring script"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    echo "Database $DB_NAME not initialized, ignoring script"
    exit 0
fi

IS_DB_INCOMPATIBLE=$(python -c "from odoo import service; print(len(service.db.list_db_incompatible(('$DB_NAME',))) > 0)")

if [ $IS_DB_INCOMPATIBLE == "True" ]
then
    echo "Database $DB_NAME is incompatible. DB is not in the same version than the code."
    exit 0
fi

echo -e "\e[0Ksection_start:$(date +%s):Click Odoo Update\r\e[0K\e[32m--- Start Update ---\e[0m"

# clear log before
rm -f /data/odoo/shared/click-odoo-update.log

echo "START UPDATING USING CLICK ODOO"
click-odoo-update --i18n-overwrite 2>&1 | tee /data/odoo/shared/click-odoo-update.log || exit 1
echo "END UPDATING USING CLICK ODOO"

echo -e "\e[0Ksection_end:$(date +%s):Click Odoo Update\r\e[0K"
