# syntax=docker/dockerfile:1.4
FROM ghcr.io/akretion/odoo-docker:{{ odoo_version }}-light-latest as base

# There is a high chance that multiple projects
# share the same odoo/src/requirements.txt
# install odoo requirements first

RUN mkdir -p /odoo/src/odoo/addons

COPY ./src/setup /odoo/src/setup
COPY ./src/setup.py /odoo/src/setup.py

COPY ./src/odoo/*.py /odoo/src/odoo/
COPY ./src/odoo/cli /odoo/src/odoo/cli
COPY ./src/odoo/conf /odoo/src/odoo/conf
COPY ./src/odoo/modules /odoo/src/odoo/modules
COPY ./src/odoo/osv /odoo/src/odoo/osv
COPY ./src/odoo/release.py /odoo/src/odoo/release.py
COPY ./src/odoo/service /odoo/src/odoo/service
COPY ./src/odoo/tests /odoo/src/odoo/tests
COPY ./src/odoo/tools /odoo/src/odoo/tools
COPY ./src/odoo/upgrade /odoo/src/odoo/upgrade
RUN /odoo/bin/pip install -e /odoo/src

FROM base as thisproject
COPY ./requirements.txt /odoo/requirements.txt
RUN /odoo/bin/pip install --no-cache-dir \
    -r /odoo/requirements.txt \
    -f https://wheelhouse.acsone.eu/manylinux2014

ENV ADDONS_PATH=/odoo/src/odoo/addons,/odoo/src/addons,/odoo/links,/odoo/local-src

COPY ./start-entrypoint.d /odoo/start-entrypoint.d
COPY ./scripts /odoo/scripts
COPY ./templates /odoo/templates


FROM thisproject as dev

# allow to pip install anything temporary
COPY ./dev_requirements.txt /odoo/dev_requirements.txt
RUN /odoo/bin/pip install --no-cache-dir \
    -r /odoo/dev_requirements.txt \
    -f https://wheelhouse.acsone.eu/manylinux2014

FROM thisproject as prod
ARG SENTRY_RELEASE=0.0.0
COPY ./src /odoo/src
RUN /odoo/bin/pip install -e /odoo/src
COPY ./external-src /odoo/external-src
COPY ./links /odoo/links
COPY ./local-src /odoo/local-src
ENV SENTRY_RELEASE=$SENTRY_RELEASE
