# syntax=docker/dockerfile:1.4
{% if odoo_version == "20.0" %}# ghcr.io/akretion/odoo-docker:20.0-light-latest is not published yet,
# we build on the 19.0-light one in the meantime (same python 3.13 on noble),
# switch back to 20.0-light-latest as soon as it is available
{% endif %}FROM ghcr.io/akretion/odoo-docker:{{ "19.0" if odoo_version == "20.0" else odoo_version }}-light-latest as base

# There is a high chance that multiple projects
# share the same odoo/src/requirements.txt
# install odoo requirements first

RUN mkdir -p /odoo/src/odoo/addons /data/odoo/shared

COPY ./src/setup /odoo/src/setup
COPY ./src/setup.py /odoo/src/setup.py

COPY ./src/odoo/*.py /odoo/src/odoo/
COPY ./src/odoo/cli /odoo/src/odoo/cli
{% if branch_name in ("14.0","15.0","16.0","17.0","18.0") %}# odoo/conf is only present up to Odoo 18
COPY ./src/odoo/conf /odoo/src/odoo/conf
{% endif %}COPY ./src/odoo/modules /odoo/src/odoo/modules
{% if branch_name in ("14.0","15.0","16.0","17.0","18.0","19.0") %}# odoo/osv is only present up to Odoo 19
COPY ./src/odoo/osv /odoo/src/odoo/osv
{% endif %}COPY ./src/odoo/release.py /odoo/src/odoo/release.py
COPY ./src/odoo/service /odoo/src/odoo/service
COPY ./src/odoo/tests /odoo/src/odoo/tests
COPY ./src/odoo/tools /odoo/src/odoo/tools
COPY ./src/odoo/upgrade /odoo/src/odoo/upgrade
RUN /odoo/bin/pip install {% if branch_name in ("14.0","15.0","16.0","17.0","18.0") %}--config-setting editable_mode=compat {%endif %}-e /odoo/src

FROM base as thisproject
COPY ./requirements.txt /odoo/requirements.txt
RUN /odoo/bin/pip install --no-cache-dir \
    -r /odoo/requirements.txt

ENV ADDONS_PATH=/odoo/src/odoo/addons,/odoo/src/addons,/odoo/links,/odoo/local-src

COPY ./start-entrypoint.d /odoo/start-entrypoint.d
COPY ./scripts /odoo/scripts
COPY ./templates /odoo/templates


FROM thisproject as dev

# allow to pip install anything temporary
COPY ./dev_requirements.txt /odoo/dev_requirements.txt
RUN /odoo/bin/pip install --no-cache-dir \
    -r /odoo/dev_requirements.txt

# Install fish shell
RUN --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y --no-install-recommends fish

FROM thisproject as prod
ARG SENTRY_RELEASE=0.0.0
COPY ./src /odoo/src
RUN /odoo/bin/pip install {% if branch_name in ("14.0","15.0","16.0","17.0","18.0") %}--config-setting editable_mode=compat {% endif %}-e /odoo/src
COPY ./external-src /odoo/external-src
COPY ./links /odoo/links
COPY ./local-src /odoo/local-src
ENV SENTRY_RELEASE=$SENTRY_RELEASE
