[pytest]
addopts = --odoo-database=dbtest -p no:warnings
capture = no
# You may fine tune filter warnings with ini syntax here
# https://docs.pytest.org/en/stable/how-to/capture-warnings.html
# in that case remove `-p no:warnings`
filterwarnings = 
    ignore::DeprecationWarning
cache_dir = /tmp/pytest_cache_dir
