#age1h8qrqg2cx4e054ywqsgcx8ej7lh7wwa0tf9me5x4sd3unq5asv5szay2uh
services:
  odoo:
    build:
      context: ./odoo
      target: prod
    image: "${BUILD_NAME}"
    environment:
      - ODOO_BASE_URL=https://${DOMAIN}
      - SENTRY=False
      - PGSSLMODE=require
      - DB_NAME=${CI_PROJECT_NAME}
      - PGDATABASE=${CI_PROJECT_NAME}
      - DB_NAME=${BUILD_NAME}
      - PGDATABASE=${BUILD_NAME}
      - DB_USER=${CI_PROJECT_NAME}
      - PGUSER=${CI_PROJECT_NAME}
      - DB_HOST=
      - PGHOST=

      # NO SSL while in local
      - ODOO_REPORT_URL=https://${DOMAIN}
      - WORKERS=2
      - MAX_CRON_THREADS=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${DOMAIN}`) && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.tls=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}middle.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}middle"
    networks:
      - traefik
      - local
    volumes:
      - type: tmpfs
        target: /data/odoo
      - type: volume
        source: filestore
        target: /data/odoo/filestore
    depends_on:
        db:
          condition: service_healthy
volumes:
  filestore:
networks:
  traefik:
    external: true
  local:
version: "3.7"
