networks:
  traefik:
    external: true
  local:
services:
  db:
    image: postgres/postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .db/data:/var/lib/postgresql/data/pgdata
    networks:
      - local
  odoo:
    build:
      context: odoo
      target: dev
    image: ${PROJECT_NAME}
    # cache_from: ${PROJECT_NAME} # main branch
    environment:
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: odoo
      PGUSER: odoo
      LIST_DB: "True"
      DB_FILTER: .*
      WITHOUT_DEMO: "False"
      WORKERS: 0
      ODOO_REPORT_URL: http://odoo:8069
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${DOMAIN}`)
        && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlAllowMethods=
        GET,POST,OPTIONS,PUT"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlAllowHeaders=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,api-key,partner-email,authorization,sess-cart-id,website-unique-key"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlExposeHeaders=Content-Length,Content-Range"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.addVaryHeader=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}corsHeader"
      - "docky.help=http://${DOMAIN}"
    links:
      - db
      - kwkhtmltopdf
    networks:
      - local
      - traefik
    volumes:
      # do not mount /odoo directly
      # we want to preserve /odoo/venv
      - ./odoo/external-src:/odoo/external-src
      - ./odoo/links:/odoo/links
      - ./odoo/local-src:/odoo/local-src
      - ./odoo/src:/odoo/src
      # data
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
      # mount home dir
      - ./.home/.bash_history:/home/odoo/.bash_history
  kwkhtmltopdf:
    image: acsone/kwkhtmltopdf
    networks:
      - local
version: "3.7"
